export const seoKeywords = [
  "Faaz Laeeq",
  "Web Developer",
  "Web Designer",
  "Portfolio",
  "reactmode",
  "UI designer",
  "Frontend developer",
  "Backend developer",
  "Fullstack developer",
  "React developer",
  "Next.js developer",
  "Node.js developer",
  "Express.js developer",
  "MongoDB developer",
  "MERN stack developer",
  "Software developer",
  "Software engineer",
  "Web developer in Pakistan",
  "Web developer in US",
];
